version: '3'

services:
  app-paracasa:
    image: paracasa:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=aplicacionmenu
    ports:
      - "3307:3306"
  app-container:
    image: app-container
    ports: 
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/aplicacionmenu
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "1234"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - app-paracasa
    

        
       